name: Deploy Laravel App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH and Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 69.62.83.32
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Masuk ke direktori aplikasi
          cd /var/www/rpm

          # Update code dengan git pull
          git pull origin main

          # Jalankan composer install
          sudo -u www-data composer install --no-dev --optimize-autoloader

          # Jalankan migrasi dan cache Laravel
          php artisan migrate
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear
          php artisan optimize:clear
          php artisan route:cache
